### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by rajachan** [jonhoo/rust-ibverbs#23]
@jonhoo @daniel-noland wondering what plans you had for this crate. Are you planning to maintain this over time or is any company  looking at sustaining the project?

**Comment by daniel-noland** [comment]
I absolutely intend to support and continue to develop on this crate.  That said, my time has been very stretched for a while now due to a large project at work.  It is my hope that my work project will wrap up in the next month or two, at which point I would love to get back to this.

I have a lot of ideas for things I would like to improve, starting with testing, and moving onto other RDMA functionality like sge lists, atomic operations, as well as performance benchmarks, as well as an investigation of link time optimization for this + rdma-core

**Comment by rajachan** [comment]
Thanks for that info, sounds great.
